class: bg-main1 split-30 hide-slide-number

.column.bg-main3[
]
.column.slide-in-right[
.sliderbox.bg-main2.vmiddle[
.font5[Por quê usar o Docker]
]]

---

class: middle center bg-main1 hide-slide-number

# Vantagens de usar o Docker:

--

  ## Configuração simplificada das imagens
  ## Melhor administração de código
  ### Evita a frase: .text-ht3["Mas na minha máquina roda"]
  ## Capacidades de encontrar problemas
  ### Facilita o processo de debug de código
        
---

class: middle center bg-main1 hide-slide-number

# Onde o Docker pode ser aplicado

--
  
  ## Todo script, código, aplicação que é desenvolvida pode ser colocada em um Container do Docker para distribuição e testes.
  
--- 

class: middle center bg-main1 hide-slide-number
  
# Onde o R entra nisso?

--
  
  ## Nos últimos anos, vêm crescendo o número de serviços que podem usar o R como linguagem base, desde aplicativos web para consulta e visualização de dados, até a criação de APIs com o Plumber.
  
  ## E todos esses serviços podem utilizar dos benefícios do Docker para facilitar a implementação!
  
---