class: bg-main1 split-30 hide-slide-number

.column.bg-main3[
]
.column.slide-in-right[
.sliderbox.bg-main2.vmiddle[
.font3[RStudio + Shiny + Plumber usando Docker]
]]

---

class: middle center bg-main1 hide-slide-number

# Projeto Rocker

--

  ## O Projeto Rocker é mantido Carl Boettiger(UC Berkeley) e Dirk Eddelbuettel(Univ. of Illinois) e pela comunidade `r icons::fontawesome("r-project")`.
  ### O objetivo do projeto é fornecer no DockerHub `r icons::fontawesome("docker")` imagens dos principais serviços que podem ser hospeados com um ambiente R.
  # .text_hl[[Rocker Project](https://www.rocker-project.org/)]

---

class: middle center bg-main1 hide-slide-number

# RStudio

--

  ## Rodando o comando abaixo no terminal, será iniciado um container com a imagem do RStudio Server na porta 8787.
  
```{sh eval = F, echo = T}
docker run -d -p 8787:8787 rocker/rstudio:3.5.3
```

---

class: middle center bg-main1 hide-slide-number

# Shiny

--

  ## Rodando o comando abaixo no terminal, será iniciado um container com a imagem do Shiny Server na porta 3838.
  
```{sh eval = F, echo = T}
docker run -d -p 3838:3838 rocker/shiny:3.5.3
```

  ## O aplicativo iniciará com dois aplicativos dummy na imagem do Shiny Server.
  
---

class: middle center bg-main1 hide-slide-number

# Plumber

--

  ## A imagem contendo o serviço Plumber não é disponibilizada pelo Projeto Rocker, mas sim pelos desenvolvedores do pacote que fornece a API.
  ## O código fonte pode ser encontrado no [GitHub `r icons::fontawesome("github")`](https://github.com/trestletech/plumber)
  
```{sh eval = F, echo = T}
docker run -p 8080:8000 trestletech/plumber:latest
```

---