class: bg-main1 split-30 hide-slide-number

.column.bg-main3[
]
.column.slide-in-right[
.sliderbox.bg-main2.vmiddle[
.font3[Conclusão]
]]

---

class: middle center bg-main1 hide-slide-number

# Utilização do Docker

--
  <div class = "bullet2">
  <ul>
  <li> O Docker pode ser uma ferramente muito útil para facilitar o desenvolvimento, debug e implantação de aplicativos e serviços. </li>
  <li> Com a crescente integração com o R, ele se mostra como um facilitador para equipes que trabalham com análise de dados publicarem seus trabalhos, garantindo maior visibilidade, com menor preocupação em manutenção de servidores </li>
  <li> Além disso, via integração com serviços como Kubernetes, é possível construir uma solução escalável para qualquer serviço desenvolvido em R. </li>
  </ul>
  </div>
---

class: middle left bg-main1 hide-slide-number

# Referências

## `r icons::fontawesome("angle-double-right")` [Docker 101: Fundamentals & The Dockerfile](https://medium.com/@paigen11/docker-101-fundamentals-the-dockerfile-b33b59d0f14b)

## `r icons::fontawesome("angle-double-right")` [An Introduction to Docker for R Users](https://colinfay.me/docker-r-reproducibility/)

## `r icons::fontawesome("angle-double-right")` [Using docker to deploy an R plumber API](https://medium.com/@skyetetra/using-docker-to-deploy-an-r-plumber-api-863ccf91516d)

## `r icons::fontawesome("angle-double-right")` [Applications with R and Docker](http://www.cascadia-analytics.com/docs/user2018-docker-r-tutorial-slides.pdf)

---

class: bg-main5 middle center hide-slide-number

## [`r icons::fontawesome("envelope-open")`](mailto:lhzpaese@gmail.com) lhzpaese@gmail.com
## [`r icons::fontawesome("github")`](https://github.com/paeselhz) https://github.com/paeselhz
## [`r icons::fontawesome("linkedin")`](https://www.linkedin.com/in/lhzpaese/) https://www.linkedin.com/in/lhzpaese/

---